### ISSUE TITLE
Cannot scroll to reveal Dashboard and Home

### ISSUE THREAD

**Issue by hanbec-ronres** [dcSpark/urbit-visor#112]
I can successfully install Visor 0.2.2  from the Chrome Extension store and add my planet (~hanbec-ronres).  However, when I select the ship, and enter my master password, the resulting window does not allow me to see the Home and Dashboard buttons as in the video on YouTube.  There doesn't seem to be a scroll function, either.

<img width="356" alt="CleanShot 2021-10-30 at 08 36 53@2x" src="https://user-images.githubusercontent.com/92059696/139533304-5e8a63e8-9fb8-46d0-8bc9-43db2e5fcb41.png">

System info:

In **Brave** ( Chromium 95.0.4638.69) on an **M1 MacBook** Air running **MacOS 12.0.1**

**Comment by mirtyl-wacdec** [comment]
That's an odd one, the ship name display is strange, the left margin is off, and it seems to be shifted downward, pushing everything else with it.

Could you open [chrome-extension://oadimaacghcacmfipakhadejgalcaepg/popup.html](chrome-extension://oadimaacghcacmfipakhadejgalcaepg/popup.html) and see what that does? There might be some error in the Javascript console.

**Comment by robkorn** [comment]
This has been addressed in the redesign update of v0.3.0.
