### ISSUE TITLE
got the extension installed; now what?

### ISSUE THREAD

**Issue by dckc** [dcSpark/urbit-visor#93]
The README skips from Load unpacked to the web page API. I could use a clue in between.

**Comment by mirtyl-wacdec** [comment]
The Visor shoould be in your browser extensions. Check it out and build things with it =)

In the meantime you can use it with the [Urbit Dashboard](https://urbitdashboard.com)

**Comment by dckc** [comment]
yes, the browser extension is installed. but I guess I should have a ship running or something? What port does the ship listen on? (I think I have mine running on a colo node on the other end of an ssh connection, but I need to know what port(s) to tunnel.)

**Comment by dckc** [comment]
I try out urbit once every 9 months or so, and I forget all the technical details in between. This thing has got me interested, but I'd like to see links to introductory urbit docs and such.

**Comment by dckc** [comment]
the extension is asking for a +code. what's that? Where do I get one? I have a key file and some other stuff but I don't know if I have a + code.

**Comment by mirtyl-wacdec** [comment]
>the extension is asking for a +code. what's that? Where do I get one? I have a key file and some other stuff but I don't know if I have a + code.

You need a running ship, and access to its console (or the web terminal). In there, enter `+code` and it will give you the login code for your ship.
As for which port your ship is listening to, if you're running the ship on your local, it will tell you shortly after booting, e.g. `http: web interface live on http://localhost:80`

**Comment by kennyrowe** [comment]
Type +code into the dojo (command line)

**Comment by dckc** [comment]
ok... I have a running ship and a + code. I can't connect, but I'll raise that as a separate issue...

**Comment by robkorn** [comment]
Thanks for giving Urbit Visor a whirl.
