### ISSUE TITLE
"Invalid URL" when connecting to ship over ssh

### ISSUE THREAD

**Issue by dckc** [dcSpark/urbit-visor#94]
I'm sitting at an Ubuntu machine, connected to a colo node over ssh. My ship is running on the colo node. I can reach it from brave and from port over the ssh tunnel.

Among the log messages from my ship is:

```
http: live (insecure, public) on 8081
```

When I open the extension, I see fields for URL and +code. I get a +code from the ship, and then put `http://localhost:8081` in the URL, and hit **Add Ship**. It spun for a sec (which was promising, considering other port numbers failed instantly) and then says **Invalid URL. Could not connect to ship**.

What other diagnostics can I gather?

**Comment by mirtyl-wacdec** [comment]
"Invalid URL" means you're likely getting a 404. The extension is part of the browser though, if you can reach the ship normally with the browser, Urbit Visor should be able to access it too.

You can open the extension in its own tab, going to [chrome-extension://facjjjhpegphdnobphgcmfjkchhngiml/popup.html](chrome-extension://facjjjhpegphdnobphgcmfjkchhngiml/popup.html) and open the browser dev tools to see what the login request is doing.

**Comment by dckc** [comment]
Under Response in the network tab for the extension dev tools I see **Failed to load response data**.

I wonder if something like the `Referrer Policy: strict-origin-when-cross-origin` that the ship seems to choose is the problem.

The extension sends this request header where plain brave does not:

```
Origin: chrome-extension://mpmcmhkkbikcpcglfkadondjkjaainoa
```

**Comment by dckc** [comment]
aha... in Manage Extensions I see some more diagnostics:

![image](https://user-images.githubusercontent.com/150986/135701300-b30820d3-da76-49d7-8c20-153cdf992c1f.png)

**Comment by mirtyl-wacdec** [comment]
Thanks for the feedback, that's useful.

Are you getting a status 200 from the POST request to `http://localhost:8080/~/login`? A successful login should return a status 204.

**Comment by dckc** [comment]
yes: **Status Code:** 200 ok

![image](https://user-images.githubusercontent.com/150986/135701476-2a70db72-1edb-495e-9a6f-f410edc4bd6a.png)

**Comment by mirtyl-wacdec** [comment]
It seems your Urbit OS version (and probably the binaries too) are quite out of date (judging by the `Server: urbit/vere-0.10.7` line).

I would stop the ship, download new binaries from [here](https://urbit.org/getting-started/cli), boot the ship again, and then run `|ota (sein:title our now our) %kids` on the dojo console. Wait for the update to apply, and then try to login on the visor again.
